### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by qpwo** [weiliansong/CS660#2]
Hey Weilian, thanks for making this. I'm running on mac, and unfortunately I got an error when I build the docker image. It runs for a while and gets pretty far, until the below error. Do you have any idea what might be causing this? If not, would it be possible for you to release a prebuilt version? Thank you!!

```
$ sudo docker-compose up --build
Password:
Creating network "docker_default" with the default driver
Building malmo
Step 1/25 : FROM consol/ubuntu-xfce-vnc
(...)
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
 :decompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileMc'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 137

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':decompileMc'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	(...)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 137

BUILD FAILED

	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
	(...)
	... 60 more

Total time: 3 mins 43.077 secs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/malmo/minecraftbootstrap.py", line 69, in download
    .format(malmo_version)])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./gradlew', 'setupDecompWorkspace', 'build', 'testClasses', '-x', 'test', '--stacktrace', '-Pversion=0.36.0']' returned non-zero exit status 1
ERROR: Service 'malmo' failed to build: The command '/bin/sh -c python3 -c "import malmo.minecraftbootstrap;malmo.minecraftbootstrap.download(buildMod=True)"' returned a non-zero code: 1
```

**Comment by weiliansong** [comment]
@qpwo can you try [this](https://github.com/Microsoft/malmo/blob/master/scripts/python-wheel/README.md#using-the-prebuilt-docker-image) instead? It uses a pre-built image released (probably) by Microsoft. If it works, then something on my end is wrong. If it doesn't work, then there might be a deeper problem...
